### PR TITLE
Update mono

### PR DESCRIPTION
**Pull request by Unrud**
Required for updating [flathub/net.openra.OpenRA](https://github.com/flathub/net.openra.OpenRA) to runtime 18.08.

### CODE REVIEW

**Comment by TingPing** [comment]
Runtime changes have to go into a new branch.

**Comment by Unrud** [comment]
> Runtime changes have to go into a new branch.

I can't create new branches.

**Comment by TingPing** [comment]
So just update it for now, open an issue requesting a branch.

**Comment by Unrud** [comment]
> So just update it for now, open an issue requesting a branch.

Opened the issue and removed the commit for the runtime.

**Comment by TingPing** [comment]
bot, build

**Pull request merged**
